// <auto-generated />
using Layui_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Layui_API.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20200722025123_652")]
    partial class _652
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Layui_API.Models.Class", b =>
                {
                    b.Property<int>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Administrator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mnumber")
                        .HasColumnType("int");

                    b.Property<string>("ShippingRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheTeam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mid");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("Layui_API.Models.Student", b =>
                {
                    b.Property<int>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mid")
                        .HasColumnType("int");

                    b.Property<string>("VLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vcolor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleFuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehiclePrices")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vid");

                    b.ToTable("students");
                });
#pragma warning restore 612, 618
        }
    }
}
