// <auto-generated />
using Layui_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System;

namespace Layui_API.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Layui_API.Models.Motorcade", b =>
                {
                    b.Property<int>("Mid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mnumber")
                        .HasColumnType("int");

                    b.Property<string>("ShippingRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Administrator")
                      .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheTeam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Mid");

                    b.ToTable("classes");
                });

            modelBuilder.Entity("Layui_API.Models.Vehicle", b =>
                {
                    b.Property<int>("Vid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Emission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Mid")
                        .HasColumnType("int");

                    b.Property<string>("VLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vcolor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vehicle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehicleFuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VehiclePrices")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Vid");

                    b.ToTable("students");
                });
            modelBuilder.Entity("Vehicle_ManagementAPI.Model.Carrier", b =>
            {
                b.Property<int>("CID")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("CarNo")
                    .HasColumnType("int");

                b.Property<string>("Estimate")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Fleet")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Numbers")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Position")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("StarTime")
                    .HasColumnType("datetime2");

                b.HasKey("CID");

                b.ToTable("carriers");
            });
            modelBuilder.Entity("Vehicle_ManagementAPI.Model.Chenben", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<int>("Cyid")
                    .HasColumnType("int");

                b.Property<string>("Endcity")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Kimiter")
                    .HasColumnType("int");

                b.Property<int>("People")
                    .HasColumnType("int");

                b.Property<string>("Startcity")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Sum")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("chenbens");
            });

            modelBuilder.Entity("Vehicle_ManagementAPI.Model.Driver", b =>
            {
                b.Property<int>("Did")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("DBelongsTeam")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DContactAddress")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DEntryTime")
                    .HasColumnType("datetime2");

                b.Property<string>("DIDNumber")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DMaritalStatus")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DName")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DPhone")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("DQuasiType")
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("DSex")
                    .HasColumnType("int");

                b.Property<DateTime>("DateOfBirth")
                    .HasColumnType("datetime2");

                b.Property<int>("Drid")
                    .HasColumnType("int");

                b.Property<string>("DrivingNumber")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Did");

                b.ToTable("drivers");
            });
#pragma warning restore 612, 618
        }
    }
}
